apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: MLE_Consume-EMS_Message
  description: ''
  tags:
    - flogo
  links:
    - title: TIBCO Flogo Enterprise
      url: https://docs.tibco.com/products/tibco-flogo-enterprise
  annotations:
    github.com/project-slug: https://github.com/idasara-sgamato/ImportFlogoAppRepo
spec:
  type: flogo
  lifecycle: production
  owner: group:default/idasara-sgamato
